export { ResourceRouterModule, ResourceRouterOptions, RESOURCE_ROUTER_CONFIGURATION } from './src/resource-router-module';
export { ViewData } from './src/view-data';
export { ViewDataLoader, HttpClientViewDataLoader } from './src/view-data-loader';
export { ViewDef, Data, StatusType } from './src/view-definition';
export { LocationInfo, parseUrl } from './src/utils/parse-url';
export { ApiUrl, BaseApiUrl, BrowserApiUrl } from './src/api-url';
export { ApiMapper } from './src/api-mapper';
export { SingleApiMapper, APP_API_PREFIX } from './src/single-api-mapper';
export { ApiLocation } from './src/api-location';
export { ResourceViewRegistry, RESOURCE_VIEWS, TYPE_QUALITY_EVALUATOR } from './src/resource-view-registry';
export { ResourceOutletComponent } from './src/directives/resource-outlet';
export { ResourceDataDirective } from './src/directives/resource-data';
export { ResourceViewDirective } from './src/directives/resource-view';
export { TypeQualityEvaluator, simpleTypeQualityEvaluator, statusQualityEvaluator } from './src/quality-evaluator';
export { NavigationHandler, supportsNavigation } from './src/navigation-handler';
export { normalizeMediaType } from './src/utils/normalize-media-type';
export * from './src/system-media-types';
export { ViewTypeStrategy, HeaderViewTypeStrategy } from './src/view-type-strategy';
export { escapeRegExpPattern, wildcardToRegex } from './src/utils/wildcard-to-regex';
export { ResourceLinkDirective } from './src/directives/resource-link';
export { ResourceLinkWithHrefDirective } from './src/directives/resource-link-with-href';
