export { ResourceRouterModule, ResourceRouterOptions } from './resource-router-module';
export { ViewData } from './view-data';
export { ViewDataLoader, HttpViewDataLoader } from './view-data-loader';
export { ViewDef, ResolveData, ResourceTypeMatcher } from './config';
export { APP_API_PREFIX, ApiUrl } from './api-url';
export { ApiLocation } from './api-location';
export { ResourceOutletDirective } from './directives/resource-outlet';
export { ApiLinkDirective } from './directives/api-link.directive';
export { ResourceDataDirective } from './directives/resource-data';
export { ResourceViewDirective } from './directives/resource-view';
