name: Build
on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    
    - uses: filipstefansson/set-npm-token-action@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    
    - name: get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    
    - name: cache npm
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: npm install and bootstrap
      run: |
        npm install
        npm run bootstrap
              
    - name: npm build and test
      run: |
        npm run build
        npm run buildapp
        
    - name: npm publish
      run: |
        if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}; then
          npm publish dist/angular-resource-router
        else
          echo "Dry run"
          npm publish --dry-run dist/angular-resource-router
        fi
        
    - name: cleanup cache
      run: npm unlink angular-resource-router
