name: Build
on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: 12

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v2.4.0
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: filipstefansson/set-npm-token-action@v1.1
      with:
        token: ${{ secrets.NPM_TOKEN }}

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache npm
      uses: actions/cache@v2.1.6
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install

    - name: Run npm bootstrap
      run: npm run bootstrap

    - name: Build and test
      run: |
        npm run build
        npm run buildapp

    - name: Package and publish
      run: |
        # NOTE buildapp target currently screws up built app, so we need to rebuild it
        rm -rf dist/
        npm run buildonly

        if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}; then
          npm publish dist/angular-resource-router
        else
          echo "Dry run"
          npm publish --dry-run dist/angular-resource-router
        fi

    - name: Prepare npm cache
      run: npm unlink angular-resource-router
